/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        weave: "#f4f3e5",
        grey: "#494343",
        clay: "#a05d37",
        red: "#ff151c",
        blue: "#00c1ff",
        yellow: "#ffc904",
        orange: "#ff8400",
        green: "#00c700",
        magenta: "#00c700",
        separators: "#d2d0c5",
        darkGrey: "#332d2d",
        introLayer: "#49230D",
        customPiecesLayer: "#653920",
      },
      fontFamily: {
        "pr-light": "var(--primaryLightFont)",
        "pr-regular": "var(--primaryRegularFont)",
        "pr-medium": "var(--primaryMediumFont)",
        "pr-bold": "var(--primaryBoldFont)",
        "sec-light": "var(--secondaryLightFont)",
        "sec-regular": "var(--secondaryRegularFont)",
        "sec-medium": "var(--secondaryMediumFont)",
      },
      fontSize: {
        overline: ["0.875rem", { lineHeight: "1.25" }],
        "overline-lg": ["1.375rem", { lineHeight: "1.25" }],
        body: ["1rem", { lineHeight: "1.5" }],
        "body-lg": ["1.25rem", { lineHeight: "1.5" }],
        "body-xl": ["1.5625rem", { lineHeight: "1.4" }],
        "body-2xl": ["2rem", { lineHeight: "1.35" }],
        caption: ["0.875rem", { lineHeight: "1.4" }],
        "caption-sm": ["1.0625rem", { lineHeight: "1.4" }],
        "footer-link": ["1.3125rem", { lineHeight: "1.2" }],
        h5: ["1.75rem", { lineHeight: "1.1" }],
        h4: ["2rem", { lineHeight: "1.1" }],
        h3: ["2.5rem", { lineHeight: "1.05" }],
        "h3-lg": ["3rem", { lineHeight: "1.05" }],
        "h3-xl": ["5rem", { lineHeight: "1" }],
        h1: ["3rem", { lineHeight: "1" }],
        "h1-md": ["4.5rem", { lineHeight: "1" }],
        "h1-lg": ["6rem", { lineHeight: "1" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-sm": "1.5rem",
        "gutter-md": "2rem",
        "gutter-lg": "2.5rem",
        "gutter-xl": "4rem",
        "section-y": "3rem",
        "section-y-md": "4rem",
        "section-y-lg": "6rem",
      },
      maxWidth: {
        prose: "36rem",
        "copy-sm": "28rem",
        "copy-md": "40rem",
        "copy-lg": "56rem",
      },
    },
  },
  plugins: [],
};
